### ISSUE TITLE
Apps not loaded on emulator when selecting Run on TV emulator

### ISSUE THREAD

**Issue by jwholme2** [chunhua-liu/vscode-extension-tizentv#1]
First, thank you for creating this extension!

My problem: I am unable to launch a basic app in the Emulator. I have a basic emulator image created but I do not see my apps populated when I view the apps on the emulator:
![image](https://user-images.githubusercontent.com/5523336/28749930-e6664c72-74a5-11e7-98bb-3d1d9cb4449d.png)

Is there some kind of manual loading process of the .wgt? 

My setup: 
My settings.json looks like:

{
    "window.zoomLevel": 1,
    "tizentv.simulatorLocation": "c:\\tizen-studio\\tools\\sec-tv-simulator",
    "tizentv.logLevel": "DEBUG",
    "tizentv.tizenStudioLocation": "C:\\tizen-studio"
}

I did the following to create a basic app to test with:
Create Web App -> TV Basic App

Thanks!

**Comment by haichao625** [comment]
The setting looks ok, but could you please provide more info like the log of "launch failed".
Thanks.

**Comment by haichao625** [comment]
The setting looks ok, but could you please provide more info like the log of "launch failed". 
Also, are you using Tizen 4.0 Emulator?

Thanks.

**Comment by jwholme2** [comment]
I am using this version of Tizen Emulator (not sure if this is 4.0 or not)
![image](https://user-images.githubusercontent.com/5523336/28950675-fa679ad6-7893-11e7-8f06-98205f8ba664.png)


There was no launch failed - that is the confusing part. I just went to the TV Emulator and looked under Apps but did not see the app installed.

![image](https://user-images.githubusercontent.com/5523336/28950817-e7cf5d54-7894-11e7-8cc0-49442c95b294.png)


This is the tail of the log
9:28:18 PM##_signPackage: Generated author-signature.xml and signature1.xml
9:28:18 PM##_signPackage: Sign the package Successfully!
9:28:18 PM##_Build Package: Completed sign...
9:28:18 PM##_Build Package: Output put has been set as: c:\code\code.wgt
9:28:18 PM##_Build Package: Move .wgt from tempory path
9:28:18 PM##_Build Package: Generated the .wgt achiver
9:28:18 PM##_Build Package: Build the package Successfully!
9:28:18 PM##_Run on Emulator: The app's name is: code
9:28:18 PM##_Run on Emulator: ==============================Run on TV Emulator end!

**Comment by haichao625** [comment]
@jwholme2  Hmm..,  I'm sorry that I can't make it clear with current information, but when I tried on my side, sucessfully as below: 
![after launched](https://user-images.githubusercontent.com/20487772/28956493-dd1e79ae-791f-11e7-934c-b7fdf7e28538.png)
So, to make it clear, could you please check below version info?
![version info - copy](https://user-images.githubusercontent.com/20487772/28956748-20b296c2-7921-11e7-9c82-68e257317b41.png)
If it is <=3.0, there should be no problem but happened, please send your built c:\code\code.wgt to me, that would be helpful to detect the issue.

**Comment by jwholme2** [comment]
Thank you. My platform version is set the same as yours - tv-samsung-3.0-x86. 

I tried creating a TV basic app, and then doing a Build Package. This is the tail end of the output (there were no errors):

11:16:34 PM##_signPackage: Generated author-signature.xml and signature1.xml
11:16:34 PM##_signPackage: Sign the package Successfully!
11:16:34 PM##_Build Package: Completed sign...
11:16:34 PM##_Build Package: Output put has been set as: c:\people\people.wgt
11:16:34 PM##_Build Package: Move .wgt from tempory path
11:16:34 PM##_Build Package: Generated the .wgt achiver
11:16:34 PM##_Build Package: Build the package Successfully!


When I checked for the people.wgt in the c::\people directory there was no .wgt file.

**Comment by haichao625** [comment]
One more question ^^,
Can you find .wgt file at C::\ (root path), and can you find the signature1.xml files in workspace?

**Comment by haichao625** [comment]
@jwholme2  
Could you please give some updates about the performance? It looks the fs permission issue or write sync issue if some file cannot be found.

**Comment by haichao625** [comment]
Long time no new information. Any problem, new problem can be opened.
