### ISSUE TITLE
Question: Is Caph still actively developed?

### ISSUE THREAD

**Issue by gautamkrishnar** [chunhua-liu/vscode-extension-tizentv#14]
Just came to know that samsung has a ui framework named caph. Is it still actively developed & production ready? 
https://developer.samsung.com/tv/develop/extension-libraries/caph-30/download/

I can see that the last version was released on Jul 15, 2016

**Comment by bouygues** [comment]
@gautamkrishnar , As I known, CAPH is still in use. Just no new APIs or new features release. FYI.

**Comment by gautamkrishnar** [comment]
Thanks @bouygues
