### ISSUE TITLE
[debugger-for-chrome] The target Tizen version cannot support debug!

### ISSUE THREAD

**Issue by rajeshchettupalli** [chunhua-liu/vscode-extension-tizentv#2]
Thanks in advance

After config launch.json, Debug application its prints below error and terminates

6:55:29 PM The Tizen version does not support the debug mode!
6:55:29 PM Debug failed!

Please help me

**Comment by haichao625** [comment]
Hi, Rajeshchettupalli,
Our solution is supporting "directly debug" feature on Tizen 3.0  TV or Emulator. For other version, you can use the "WebInspector Debug" feature in Command Palette. PS: Tizen 4.0 may be supported in feature:)
