### ISSUE TITLE
Build Package Error

### ISSUE THREAD

**Issue by vfernandes0408** [chunhua-liu/vscode-extension-tizentv#22]
17:52:22##_Build Package: Remove existing c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/developer/active_cert/tizen_developer_cert.pem
17:52:22##_<WARNING>_## Build Package: The existing c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/distributor/active_cert/tizen_distributor_private_key.pem will be removed firstly
17:52:22##_Build Package: Remove existing c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/distributor/active_cert/tizen_distributor_private_key.pem
17:52:22##_<WARNING>_## Build Package: The existing c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/distributor/active_cert/tizen_distributor_cert.pem will be removed firstly
17:52:22##_Build Package: Remove existing c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/distributor/active_cert/tizen_distributor_cert.pem
17:52:22##_Build Package: Signing app, please wait...
17:52:22##_signPackage: ==============================Signature Package start!
17:52:22##_signPackage: If it is debug mode, set workspace to current directory
17:52:22##_P12ToPem: ================Check Active Profile
17:52:22##_P12ToPem: ================Load Profile
17:52:22##_P12ToPem: Profile file path:c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/profiles.xml
17:52:22##_P12ToPem: Active profile name:tizentvapp
17:52:22##_P12ToPem: Find active profile:tizentvapp
17:52:22##_P12ToPem: Developer p12 File: c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/Author/tizentvapp.p12
17:52:22##_P12ToPem: Distributor p12 File: c:\Users\vfernandes\.vscode\extensions\tizensdk.tizentv-1.0.2/resource/certificate-generator/certificates/distributor/tizen-distributor-signer.p12
17:52:22##_P12ToPem: authorPassword:dWf3heiPmZxRi106UXqmRg==
17:52:22##_P12ToPem: distributorPassword:Vy63flx5JBMc5GA4iEf8oFy+8aKE7FX/+arrDcO4I5k=
17:52:22##_<WARNING>_## Build Package: Do application signature failed, please check your environment
17:52:22##_<WARNING>_## Build Package: xmldom is suggested for signature package
17:52:22##_Build Package: NaN
17:52:22##_<ERROR>_## Build Package: Failed to build package!
17:52:22##_WebInspector on TV: ================runApp
17:52:22##_WebInspector on TV: outputFullPath =c:\dev\tv\teste-app\teste-app.wgt

**Comment by huangdaman** [comment]
@bouygues I get the same error when update vscode version. 
Now only use this plugin in the 1.3.5 version of vscode。
Can you help our?

**Comment by bouygues** [comment]
> 
> 
> @bouygues I get the same error when update vscode version.
> Now only use this plugin in the 1.3.5 version of vscode。
> Can you help our?

Please try it on the latest version (v1.0.3). 
Thanks for your feedback.

**Comment by huangdaman** [comment]
> > @bouygues I get the same error when update vscode version.
> > Now only use this plugin in the 1.3.5 version of vscode。
> > Can you help our?
> 
> Please try it on the latest version (v1.0.3).
> Thanks for your feedback.

Thanks for your reply, but now the 1.02 version on vscode extensions. Can you post version 1.03 on the vscode extension? Thanks

**Comment by huangdaman** [comment]
@bouygues  hey guy! Did you published a new version

**Comment by bouygues** [comment]
> 
> 
> @bouygues hey guy! Did you published a new version

You can find the latest extension here: https://github.com/Samsung/vscode-extension-tizentv/tree/821a34e55cf08597a96f53778ad21f0bf2bace70
1. copy the latest extension to your target folder: C:\Users\[your_account]\.vscode\extensions\
2. create a certification profile if you dont have; > tizen:certification manager 
3. then, build your web package.
