### ISSUE TITLE
[Run on TV] Failed to launch the App, please check

### ISSUE THREAD

**Issue by anderson-ads** [chunhua-liu/vscode-extension-tizentv#4]
Using the Tizen Studio 2.0 with tizen 3.0 tools the app run ok on our TV (KU7500), but with the vscode-extension-tizentv after the "Run on TV" command, the app does not start, it fail to launch the app and display a popup saying to try again later.

message recieved:
09:05:22##_Run on TV: Generate the .wgt file successfully
09:05:23##_Run on TV: Trying to push the wgt to target device
09:05:24##_Run on TV: Pushed the widget target device successfully
09:05:25##_Run on TV: Start to install wgt to the device
09:05:26##_Run on TV: Install the wgt successfully
09:05:26##_Run on TV: Start to launch the app
09:05:26##_<ERROR>_## Run on TV: Failed to launch the App, please check

**Comment by wei12jiang** [comment]
First you can use "Build Package" to make .wgt, then install and launch the .wgt manually . If no problem, you can open debug log , before "Run on TV", as the README.md, File > Preferences > User Settings or Code >Preferences > User Settings, add "tizentv.logLevel":"DEBUG"
