### ISSUE TITLE
Run on TV: hangs on uninstalling package

### ISSUE THREAD

**Issue by vitalets** [chunhua-liu/vscode-extension-tizentv#5]
When I try to run app on TV (2.4) the plugin hangs on this line:
```
18:04:17##_Run on TV: Generate the .wgt file successfully
18:04:17##_Run on TV: ================runAppOnTizen 2.4
18:04:17##_Run on TV: uninstallCommand:"/Users/vitalets/tizen-studio/tools/sdb" -s 87.250.238.239 uninstall 3oO7KVBE6A
```
and the app does not launched on TV.

If I execute uninstalling command in terminal - it does not hang itself:
```
vitalets:~/projects/temp$ "/Users/vitalets/tizen-studio/tools/sdb" -s 87.250.238.239 uninstall 3oO7KVBE6A
closed
vitalets:~/projects/temp$ 
```

Could you help how to fix it?

**Comment by vitalets** [comment]
But if I use WAS_COMMAND_UNINSTALL - uninstall works:
```
sdb -s 87.250.238.239 shell 0 vd_appuninstall 3oO7KVBE6A
uninstall 3oO7KVBE6A
app_id[3oO7KVBE6A] uninstall start
app_id[3oO7KVBE6A.YandexVideo] uninstall completed
spend time for wascmd is [9576]ms
cmd_ret:0
```

It seems the plugin uses different sdb uninstall commands in two places:
[first](https://github.com/Samsung/vscode-extension-tizentv/blob/fe11d3dc43b8e47adbaea83b81d28ee0667a5fb8/launchTarget.js#L252):
```
var uninstallCommand =  SDB_PATH + SPACE + SDB_OPT_SERIAL + SPACE + SDB_COMMAND_UNINSTALL + SPACE + packageId;
```
[second](https://github.com/Samsung/vscode-extension-tizentv/blob/fe11d3dc43b8e47adbaea83b81d28ee0667a5fb8/launchTarget.js#L314):
```
var uninstallCommand =  SDB_PATH + SPACE + SDB_OPT_SERIAL + SPACE + WAS_COMMAND_UNINSTALL + SPACE + appId;
```

**Comment by wei12jiang** [comment]
"run on TV " only activity on tizen3.0 and tizen4.0

**Comment by wei12jiang** [comment]
You can try to update the tv version , connect is ok in the newest version .
