### ISSUE TITLE
Tizen 2.4 support

### ISSUE THREAD

**Issue by frankvdb7** [chunhua-liu/vscode-extension-tizentv#7]
Hello, 

When I try to debug on a Tizen 2.4 TV, the extension says "The target Tizen version cannot support debug!"

However, I can debug the application just fine with the Tizen IDE on the Tizen 2.4 TV.

Thanks,

**Comment by wei12jiang** [comment]
Vscode-extension-tizentv do not support debug(F5) on Tizen2.4 TV. But you can press "F1" to use other features.
