### ISSUE TITLE
Feature: Ability to set custom working directory

### ISSUE THREAD

**Issue by frankvdb7** [chunhua-liu/vscode-extension-tizentv#8]
Hello,

I want to be able to set a custom working directory, instead of the default working directory folder that is set in VSCode. 

For example, when my default working directory is "c:/project/tizenapp". I want to select "wwwroot" as the custom working directory. If the package command is executed, it'll package the "c:/project/tizenapp/wwwroot" directory, instead of my root working directory at "c:/project/tizenapp/".

Thanks,

**Comment by wei12jiang** [comment]
you can click File--Open Folder--then select  your directory(c:/project/tizenapp/wwwroot), then the workspace changed to your directory
