### ISSUE TITLE
Error creating project in Ubuntu linux

### ISSUE THREAD

**Issue by abbyjeet** [chunhua-liu/vscode-extension-tizentv#9]
First of all thank you for creating this extension!

Tizen Studio eclipse-based IDE is horrendous.

Just when I was thinking of developing my own vscode extension for Tizen, I found this and couldn't be happier. This extension needs to get much more exposure over eclipse based IDE.

It works much better - flawless and fast - when I open the existing project.
But I am having problem creating a new one (see the screenshot)

The OS I am using is Ubuntu 18.04

Also I am ensuring that the directory path exists.

![tizentvcreateproject](https://user-images.githubusercontent.com/1262108/39417225-28080ecc-4c96-11e8-8200-bf680cad3125.gif)

**Comment by wei12jiang** [comment]
the path "/home/git/" will be the project work space, and the "zitto" will be the project name, you should ensure the "/home/git/" exsit and "zitto" in "/home/git/" is not exsit.
